In [10]:
import sidrapy
import pandas as pd

In [12]:
tabelas = pd.read_csv('codigos_tabelas.txt',sep='\t', header=None)
tabelas

,1,"Receita operacional líquida e subvenções das empresas de transporte rodoviário com 20 ou mais pessoas ocupadas, segundo os produtos/serviços prestados"
0,2,População ocupada de 15 anos e mais por setor ...
1,3,População ocupada de 15 anos e mais por posiçã...
2,4,Taxa de desemprego aberto - semana por sexo (s...
3,5,Taxa de desemprego aberto - semana por setor d...
4,6,"Rendimento médio nominal, do trabalho principa..."
...,...,...
8513,9724,Domicílios particulares permanentes ocupados c...
8514,9725,Domicílios particulares permanentes ocupados l...
8515,9726,Domicílios particulares permanentes ocupados c...
8516,9727,Domicílios particulares permanentes ocupados e...
8517,9728,Domicílios particulares permanentes ocupados e...

In [7]:
data = sidrapy.get_table(table_code="5917", territorial_level="3", ibge_territorial_code="all", period="last 12")
data

,NC,NN,MC,MN,V,D1C,D1N,D2C,D2N,D3C,D3N,D4C,D4N
0,Nível Territorial (Código),Nível Territorial,Unidade de Medida (Código),Unidade de Medida,Valor,Unidade da Federação (Código),Unidade da Federação,Trimestre (Código),Trimestre,Variável (Código),Variável,Sexo (Código),Sexo
1,3,Unidade da Federação,1572,Mil pessoas,...,11,Rondônia,202004,4º trimestre 2020,606,População,6794,Total
2,3,Unidade da Federação,2,%,...,11,Rondônia,202004,4º trimestre 2020,6541,Coeficiente de variação - População,6794,Total
3,3,Unidade da Federação,2,%,...,11,Rondônia,202004,4º trimestre 2020,608,Percentual da população,6794,Total
4,3,Unidade da Federação,2,%,...,11,Rondônia,202004,4º trimestre 2020,6542,Coeficiente de variação - Percentual da população,6794,Total
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1292,3,Unidade da Federação,2,%,-,53,Distrito Federal,202302,2º trimestre 2023,6542,Coeficiente de variação - Percentual da população,6794,Total
1293,3,Unidade da Federação,1572,Mil pessoas,3172,53,Distrito Federal,202303,3º trimestre 2023,606,População,6794,Total
1294,3,Unidade da Federação,2,%,0.0,53,Distrito Federal,202303,3º trimestre 2023,6541,Coeficiente de variação - População,6794,Total
1295,3,Unidade da Federação,2,%,100.0,53,Distrito Federal,202303,3º trimestre 2023,608,Percentual da população,6794,Total
1296,3,Unidade da Federação,2,%,-,53,Distrito Federal,202303,3º trimestre 2023,6542,Coeficiente de variação - Percentual da população,6794,Total